### ISSUE TITLE
No hardware acceleration

### ISSUE THREAD

**Issue by chadchoi** [Blaukovitch/Mozilla_Firefox_Windows_7#13]
Confirmed via `about:support`. It said very clearly the software based D3D11 renderer is being used for WebRender.

This feature works on r3dfox and Firefox-for-windows-7.

p/s: I'm on Windows 8.1

**Comment by Blaukovitch** [comment]
Hi! problem is solved?>

**Comment by chadchoi** [comment]
> Hi! problem is solved?>

The next time please at least leave a comment to show me that you are investigating the problem. I think you didn't care, so I closed the issue. BTW, thank you very much. I will test and report back.

**Comment by chadchoi** [comment]
@Blaukovitch I don't see the updated version. Still the one being released 3 weeks ago.

**Comment by chadchoi** [comment]
@i486 Why the thumb down? What did I said wrong? Github Releases still the old version:

https://github.com/Blaukovitch/Mozilla_Firefox_Windows_7/releases

I only want to get the updated version. Hardware acceleration is essential for me.

**Comment by chadchoi** [comment]
> Hi! problem is solved?>

I didn't notice the question mark (because there is a > character next to it). It turns out that this is a question and not a statement. Since we misunderstood each other and the problem is still there, I will reopen this issue.

**Comment by chadchoi** [comment]
`media.hardware-video-decoding.failed` is always set to `true` by the browser. I tried to set `media.hardware-video-decoding.force-enabled` to `true` but it doesn't help.

Here is the relevant information from `about:support`:

```
```
Graphics
--------

Features
Window Device Pixel Ratios: 1.25
Compositing: WebRender (Software D3D11)
Font Visibility Debug Info: Windows Platform
Asynchronous Pan/Zoom: wheel input enabled; scrollbar drag enabled; keyboard enabled; autoscroll enabled; smooth pinch-zoom enabled
WebGL 1 Driver WSI Info: outOfProcess: false inProcess: true EGL_VENDOR: Google Inc. (Intel) EGL_VERSION: 1.5 (ANGLE 2.1.19739 git hash: 419cd2c3213b) EGL_EXTENSIONS: EGL_EXT_create_context_robustness EGL_ANGLE_d3d_share_handle_client_buffer EGL_ANGLE_d3d_texture_client_buffer EGL_ANGLE_surface_d3d_texture_2d_share_handle EGL_ANGLE_query_surface_pointer EGL_ANGLE_window_fixed_size EGL_ANGLE_keyed_mutex EGL_ANGLE_surface_orientation EGL_ANGLE_direct_composition EGL_NV_post_sub_buffer EGL_KHR_create_context EGL_KHR_image EGL_KHR_image_base EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image EGL_KHR_get_all_proc_addresses EGL_KHR_stream EGL_KHR_stream_consumer_gltexture EGL_NV_stream_consumer_gltexture_yuv EGL_ANGLE_stream_producer_d3d_texture EGL_ANGLE_create_context_webgl_compatibility EGL_CHROMIUM_create_context_bind_generates_resource EGL_CHROMIUM_sync_control EGL_EXT_pixel_format_float EGL_KHR_surfaceless_context EGL_ANGLE_display_texture_share_group EGL_ANGLE_display_semaphore_share_group EGL_ANGLE_create_context_client_arrays EGL_ANGLE_program_cache_control EGL_ANGLE_robust_resource_initialization EGL_ANGLE_create_context_extensions_enabled EGL_ANDROID_blob_cache EGL_ANDROID_recordable EGL_ANGLE_image_d3d11_texture EGL_ANGLE_create_context_backwards_compatible EGL_KHR_no_config_context EGL_KHR_create_context_no_error EGL_KHR_reusable_sync EGL_EXTENSIONS(nullptr): EGL_EXT_client_extensions EGL_EXT_device_query EGL_EXT_platform_base EGL_EXT_platform_device EGL_ANGLE_platform_angle EGL_ANGLE_platform_angle_d3d EGL_ANGLE_platform_angle_device_id EGL_ANGLE_device_creation EGL_ANGLE_device_creation_d3d11 EGL_ANGLE_experimental_present_path EGL_KHR_client_get_all_proc_addresses EGL_KHR_debug EGL_ANGLE_feature_control
WebGL 1 Driver Renderer: Google Inc. (Intel) -- ANGLE (Intel, Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0, D3D11-10.18.14.5180)
WebGL 1 Driver Version: OpenGL ES 3.0.0 (ANGLE 2.1.19739 git hash: 419cd2c3213b)
WebGL 1 Driver Extensions: GL_AMD_performance_monitor GL_ANGLE_base_vertex_base_instance GL_ANGLE_base_vertex_base_instance_shader_builtin GL_ANGLE_client_arrays GL_ANGLE_copy_texture_3d GL_ANGLE_depth_texture GL_ANGLE_framebuffer_blit GL_ANGLE_framebuffer_multisample GL_ANGLE_get_serialized_context_string GL_ANGLE_get_tex_level_parameter GL_ANGLE_instanced_arrays GL_ANGLE_lossy_etc_decode GL_ANGLE_memory_size GL_ANGLE_multi_draw GL_ANGLE_multiview_multisample GL_ANGLE_pack_reverse_row_order GL_ANGLE_program_cache_control GL_ANGLE_provoking_vertex GL_ANGLE_request_extension GL_ANGLE_robust_client_memory GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ANGLE_texture_multisample GL_ANGLE_texture_usage GL_ANGLE_translated_shader_source GL_CHROMIUM_bind_generates_resource GL_CHROMIUM_bind_uniform_location GL_CHROMIUM_copy_compressed_texture GL_CHROMIUM_copy_texture GL_CHROMIUM_lose_context GL_CHROMIUM_sync_query GL_EXT_EGL_image_external_wrap_modes GL_EXT_base_instance GL_EXT_blend_func_extended GL_EXT_blend_minmax GL_EXT_clip_control GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_discard_framebuffer GL_EXT_disjoint_timer_query GL_EXT_draw_buffers GL_EXT_draw_buffers_indexed GL_EXT_draw_elements_base_vertex GL_EXT_float_blend GL_EXT_frag_depth GL_EXT_instanced_arrays GL_EXT_map_buffer_range GL_EXT_multi_draw_indirect GL_EXT_multisampled_render_to_texture GL_EXT_occlusion_query_boolean GL_EXT_read_format_bgra GL_EXT_robustness GL_EXT_sRGB GL_EXT_shader_texture_lod GL_EXT_texture_compression_bptc GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_compression_s3tc_srgb GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_EXT_texture_norm16 GL_EXT_texture_rg GL_EXT_texture_storage GL_EXT_texture_type_2_10_10_10_REV GL_EXT_unpack_subimage GL_KHR_debug GL_KHR_parallel_shader_compile GL_KHR_robust_buffer_access_behavior GL_NV_EGL_stream_consumer_external GL_NV_fence GL_NV_framebuffer_blit GL_NV_pack_subimage GL_NV_pixel_buffer_object GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_image_external_essl3 GL_OES_compressed_EAC_R11_signed_texture GL_OES_compressed_EAC_R11_unsigned_texture GL_OES_compressed_EAC_RG11_signed_texture GL_OES_compressed_EAC_RG11_unsigned_texture GL_OES_compressed_ETC2_RGB8_texture GL_OES_compressed_ETC2_RGBA8_texture GL_OES_compressed_ETC2_punchthroughA_RGBA8_texture GL_OES_compressed_ETC2_punchthroughA_sRGB8_alpha_texture GL_OES_compressed_ETC2_sRGB8_alpha8_texture GL_OES_compressed_ETC2_sRGB8_texture GL_OES_depth24 GL_OES_depth32 GL_OES_draw_buffers_indexed GL_OES_draw_elements_base_vertex GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_get_program_binary GL_OES_mapbuffer GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_surfaceless_context GL_OES_texture_border_clamp GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_texture_stencil8 GL_OES_vertex_array_object GL_OVR_multiview GL_OVR_multiview2 GL_WEBGL_video_texture
WebGL 1 Extensions: ANGLE_instanced_arrays EXT_blend_minmax EXT_color_buffer_half_float EXT_float_blend EXT_frag_depth EXT_shader_texture_lod EXT_sRGB EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic MOZ_debug OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_float_linear OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_depth_texture WEBGL_draw_buffers WEBGL_lose_context WEBGL_provoking_vertex
WebGL 2 Driver WSI Info: outOfProcess: false inProcess: true EGL_VENDOR: Google Inc. (Intel) EGL_VERSION: 1.5 (ANGLE 2.1.19739 git hash: 419cd2c3213b) EGL_EXTENSIONS: EGL_EXT_create_context_robustness EGL_ANGLE_d3d_share_handle_client_buffer EGL_ANGLE_d3d_texture_client_buffer EGL_ANGLE_surface_d3d_texture_2d_share_handle EGL_ANGLE_query_surface_pointer EGL_ANGLE_window_fixed_size EGL_ANGLE_keyed_mutex EGL_ANGLE_surface_orientation EGL_ANGLE_direct_composition EGL_NV_post_sub_buffer EGL_KHR_create_context EGL_KHR_image EGL_KHR_image_base EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image EGL_KHR_get_all_proc_addresses EGL_KHR_stream EGL_KHR_stream_consumer_gltexture EGL_NV_stream_consumer_gltexture_yuv EGL_ANGLE_stream_producer_d3d_texture EGL_ANGLE_create_context_webgl_compatibility EGL_CHROMIUM_create_context_bind_generates_resource EGL_CHROMIUM_sync_control EGL_EXT_pixel_format_float EGL_KHR_surfaceless_context EGL_ANGLE_display_texture_share_group EGL_ANGLE_display_semaphore_share_group EGL_ANGLE_create_context_client_arrays EGL_ANGLE_program_cache_control EGL_ANGLE_robust_resource_initialization EGL_ANGLE_create_context_extensions_enabled EGL_ANDROID_blob_cache EGL_ANDROID_recordable EGL_ANGLE_image_d3d11_texture EGL_ANGLE_create_context_backwards_compatible EGL_KHR_no_config_context EGL_KHR_create_context_no_error EGL_KHR_reusable_sync EGL_EXTENSIONS(nullptr): EGL_EXT_client_extensions EGL_EXT_device_query EGL_EXT_platform_base EGL_EXT_platform_device EGL_ANGLE_platform_angle EGL_ANGLE_platform_angle_d3d EGL_ANGLE_platform_angle_device_id EGL_ANGLE_device_creation EGL_ANGLE_device_creation_d3d11 EGL_ANGLE_experimental_present_path EGL_KHR_client_get_all_proc_addresses EGL_KHR_debug EGL_ANGLE_feature_control
WebGL 2 Driver Renderer: Google Inc. (Intel) -- ANGLE (Intel, Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0, D3D11-10.18.14.5180)
WebGL 2 Driver Version: OpenGL ES 3.0.0 (ANGLE 2.1.19739 git hash: 419cd2c3213b)
WebGL 2 Driver Extensions: GL_AMD_performance_monitor GL_ANGLE_base_vertex_base_instance GL_ANGLE_base_vertex_base_instance_shader_builtin GL_ANGLE_client_arrays GL_ANGLE_copy_texture_3d GL_ANGLE_depth_texture GL_ANGLE_framebuffer_blit GL_ANGLE_framebuffer_multisample GL_ANGLE_get_serialized_context_string GL_ANGLE_get_tex_level_parameter GL_ANGLE_instanced_arrays GL_ANGLE_lossy_etc_decode GL_ANGLE_memory_size GL_ANGLE_multi_draw GL_ANGLE_multiview_multisample GL_ANGLE_pack_reverse_row_order GL_ANGLE_program_cache_control GL_ANGLE_provoking_vertex GL_ANGLE_request_extension GL_ANGLE_robust_client_memory GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ANGLE_texture_multisample GL_ANGLE_texture_usage GL_ANGLE_translated_shader_source GL_CHROMIUM_bind_generates_resource GL_CHROMIUM_bind_uniform_location GL_CHROMIUM_copy_compressed_texture GL_CHROMIUM_copy_texture GL_CHROMIUM_lose_context GL_CHROMIUM_sync_query GL_EXT_EGL_image_external_wrap_modes GL_EXT_base_instance GL_EXT_blend_func_extended GL_EXT_blend_minmax GL_EXT_clip_control GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_discard_framebuffer GL_EXT_disjoint_timer_query GL_EXT_draw_buffers GL_EXT_draw_buffers_indexed GL_EXT_draw_elements_base_vertex GL_EXT_float_blend GL_EXT_frag_depth GL_EXT_instanced_arrays GL_EXT_map_buffer_range GL_EXT_multi_draw_indirect GL_EXT_multisampled_render_to_texture GL_EXT_occlusion_query_boolean GL_EXT_read_format_bgra GL_EXT_robustness GL_EXT_sRGB GL_EXT_shader_texture_lod GL_EXT_texture_compression_bptc GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_compression_s3tc_srgb GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_EXT_texture_norm16 GL_EXT_texture_rg GL_EXT_texture_storage GL_EXT_texture_type_2_10_10_10_REV GL_EXT_unpack_subimage GL_KHR_debug GL_KHR_parallel_shader_compile GL_KHR_robust_buffer_access_behavior GL_NV_EGL_stream_consumer_external GL_NV_fence GL_NV_framebuffer_blit GL_NV_pack_subimage GL_NV_pixel_buffer_object GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_image_external_essl3 GL_OES_compressed_EAC_R11_signed_texture GL_OES_compressed_EAC_R11_unsigned_texture GL_OES_compressed_EAC_RG11_signed_texture GL_OES_compressed_EAC_RG11_unsigned_texture GL_OES_compressed_ETC2_RGB8_texture GL_OES_compressed_ETC2_RGBA8_texture GL_OES_compressed_ETC2_punchthroughA_RGBA8_texture GL_OES_compressed_ETC2_punchthroughA_sRGB8_alpha_texture GL_OES_compressed_ETC2_sRGB8_alpha8_texture GL_OES_compressed_ETC2_sRGB8_texture GL_OES_depth24 GL_OES_depth32 GL_OES_draw_buffers_indexed GL_OES_draw_elements_base_vertex GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_get_program_binary GL_OES_mapbuffer GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_surfaceless_context GL_OES_texture_border_clamp GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_texture_stencil8 GL_OES_vertex_array_object GL_OVR_multiview GL_OVR_multiview2 GL_WEBGL_video_texture
WebGL 2 Extensions: EXT_color_buffer_float EXT_float_blend EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic MOZ_debug OES_draw_buffers_indexed OES_texture_float_linear OVR_multiview2 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_provoking_vertex
Target Frame Rate: 60
WebGPU Default Adapter: { "navigator.gpu": null }
WebGPU Fallback Adapter: { "navigator.gpu": null }
DirectWrite: true (6.3.9600.17415)
GPU #1
Active: Yes
Description: Intel(R) HD Graphics 4600
Vendor ID: 0x8086
Device ID: 0x0412
Driver Version: 10.18.14.5180
Driver Date: 3-9-2021
Drivers: igdumdim64 igd10iumd64 igd10iumd64 igdumdim32 igd10iumd32 igd10iumd32
Subsys ID: 78171462
RAM: 0
GPU #2
Active: No
RAM: 0
Diagnostics
AzureCanvasBackend: skia
AzureCanvasBackend (UI Process): skia
AzureContentBackend: skia
AzureContentBackend (UI Process): skia
AzureFallbackCanvasBackend (UI Process): skia
CMSOutputProfile: AAACkExpbm8CEAAAbW50clJHQiBYWVogB9gABAABABQACgAeYWNzcE1TRlQAAAAASFAAADIzVGcAAAAAAAAAAAAAAAAAAPbWAAEAAAAA0ytIWFogAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALZGVzYwAAAQgAAABlY3BydAAAAXAAAABKd3RwdAAAAbwAAAAUclRSQwAAAdAAAAAOZ1RSQwAAAdAAAAAOYlRSQwAAAdAAAAAOclhZWgAAAeAAAAAUZ1hZWgAAAfQAAAAUYlhZWgAAAggAAAAUZG1uZAAAAhwAAAByZG1kZAAAAQgAAABlZGVzYwAAAAAAAAALSFAgTFAyMjc1dwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB0ZXh0AAAAAENvcHlyaWdodCAoYykgSGV3bGV0dC1QYWNrYXJkIENvbXBhbnksIDIwMDgsIEFsbCBSaWdodHMgUmVzZXJ2ZWQuAAAAWFlaIAAAAAAAAPNRAAEAAAABFsxjdXJ2AAAAAAAAAAECMwAAWFlaIAAAAAAAAG+gAAA49QAAA5BYWVogAAAAAAAAYpcAALeHAAAY2VhZWiAAAAAAAAAknwAAD4QAALbDZGVzYwAAAAAAAAAYSGV3bGV0dC1QYWNrYXJkIENvbXBhbnkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
Display0: 1680x1050@59Hz scales:1.000000|1.250000
DisplayCount: 1
HardwareStretching: both=0 window-only=0 full-screen-only=0 none=0 error=1
GPUProcessPid: 2744
ClearType Parameters: Gamma: 1.8 Pixel Structure: RGB ClearType Level: 100 Enhanced Contrast: 50
Font Visibility Debug Info: Windows Platform
Decision Log
HW_COMPOSITING:
default: available,
D3D11_COMPOSITING:
default: available,
DIRECT2D:
default: disabled, Disabled by default, Blocklisted; failure code FEATURE_FAILURE_DISABLED
D3D11_HW_ANGLE:
default: available,
GPU_PROCESS:
default: available,
WEBRENDER:
default: available,
runtime: unavailable, WebRender initialization failed, Blocklisted; failure code RcANGLE(no compositor window)_FIRST
WEBRENDER_COMPOSITOR:
default: available,
WEBRENDER_PARTIAL:
default: available,
WEBRENDER_SHADER_CACHE:
default: available,
WEBRENDER_OPTIMIZED_SHADERS:
default: available,
WEBRENDER_ANGLE:
default: available,
WEBRENDER_DCOMP_PRESENT:
default: available,
WEBRENDER_SCISSORED_CACHE_CLEARS:
default: available,
env: blocklisted, Blocklisted by gfxInfo, Blocklisted due to known issues: bug 1603515
WEBGPU:
default: available,
runtime: blocked, WebGPU cannot be enabled in release or beta, Blocklisted; failure code WEBGPU_DISABLE_RELEASE_OR_BETA
WINDOW_OCCLUSION:
default: available,
HW_DECODED_VIDEO_ZERO_COPY:
default: available,
VP8_HW_DECODE:
default: available,
env: blocklisted, #BLOCKLIST_FEATURE_FAILURE_BUG_1760464, Blocklisted due to known issues: bug 1760464
VP9_HW_DECODE:
default: available,
REUSE_DECODER_DEVICE:
default: available,
BACKDROP_FILTER:
default: available,
CANVAS_RENDERER_THREAD:
default: available,
ACCELERATED_CANVAS2D:
default: available,
REMOTE_CANVAS:
default: available,
runtime: blocked, Disabled without Direct2D, Blocklisted; failure code FEATURE_REMOTE_CANVAS_NO_DIRECT2D


Failure Log
(#0) Error: Failed to connect WebRenderBridgeChild. isParent=true
(#1) Error: Fallback WR to SW-WR + D3D11
(#2): GP+[GFX1-]: RcANGLE(no compositor window)

Media
-----

Audio Backend: (remote error)
Max Channels: 0
Preferred Sample Rate: 44100
Roundtrip latency (standard deviation): ...
Codec Support Information:
Codec Name: Software Decoding, Hardware Decoding
H264: Supported, Unsupported
VP9: Supported, Unsupported
VP8: Supported, Unsupported
AV1: Supported, Unsupported
HEVC: Unsupported, Unsupported
AAC: Supported, Unsupported
MP3: Supported, Unsupported
Opus: Supported, Unsupported
Vorbis: Supported, Unsupported
FLAC: Supported, Unsupported
Wave: Supported, Unsupported
Output Devices
Name: Group, Vendor, State, Preferred, Format, Channels, Rate, Latency
Input Devices
Name: Group, Vendor, State, Preferred, Format, Channels, Rate, Latency

Enumerate database
Content Decryption Modules Information
Key System Name: Video Robustness, Audio Robustness, Capabilities, Clear Lead, HDCP 2.2 Compatible

Sandbox
-------

Content Process Sandbox Level: 8
Effective Content Process Sandbox Level: 8
Win32k Lockdown State for Content Process: Win32k Lockdown disabled -- Operating system not supported
GPU Process Sandbox Level: 1
```
```

**Comment by Blaukovitch** [comment]
@chadchoi, Yes, I understand your problems. I try to give time to **everyone**, I have a lot of requests for crack and a lot of work on other projects - gradually fixing the existing problems. I will try to help you for sure, but unfortunately it is not fast, yes ^/

**Comment by chadchoi** [comment]
I switched to https://github.com/e3kskoy7wqk/Firefox-for-windows-7.
